spring:
  sql:
    init:
      mode: always
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/factory_db
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

